CAR_PROPERTIES = [
    "carName",
    "year",
    "engine",
    "current_km",
    "hand",
    "gearbox",
    "color",
    "original_ownership",
    "next_test",
    "annual_licensing_fee"
]


SPECIFICATIONS_PROPERTIES_TRANSLATIONS = {
    "טורבו": "turbo",
    "רמת גימור": "finish_level",
    "מספר דלתות": "number_of_doors",
    "מקומות ישיבה": "number_of_seats",
    "צריכת דלק ממוצעת (ק''מ/ליטר)": "avrage_fuel_consumption",
    "צריכת דלק בינעירונית (ק''מ/ליטר)": "avrage_fuel_consumption_city",
    "צריכת דלק עירונית (ק''מ/ליטר)": "avrage_fuel_consumption_highway",
    "סוג דלק": "fuel_type",
    "תיבת הילוכים": "gearbox",
    "הספק מירבי (כ''ס)": "horsepower",
    "מהירות מירבית (קמ''ש)": "max_speed",
    "מומנט מירבי (קג''מ)": "max_torque",
    "מספר צילינדרים": "number_of_cylinders",
    "מספר הילוכים": "number_of_gears",
    "סל''ד להספק מירבי": "rounds_per_minute_for_max_power",
    "סל''ד למומנט מירבי": "rounds_per_minute_for_max_torque",
    "אפס למאה קמ''ש (שניות)": "zero_to_100_km_in_seconds",
    "אורות גבוהים אוטומטיים": "automatic_high_beam",
    "מערכת לניטור רכב בשטח מת": "dead_vehicle_monitoring_system",
    "מערכת לבלימת חירום עצמאית": "independent_emergency_break",
    "ABS": "abs",
    "פנסים עוקבי פנייה": "turn_tracking_headlights",
    "ביטול כרית אוויר לנוסע": "cancel_airbag",
    "איזופיקס (ISOFIX)": "isofix",
    "מערכת להתרעת סטייה מנתיב": "lane_departure_warning_system",
    "מספר כריות אוויר": "number_of_airbags",
    "אזהרת חגורת בטיחות": "seat_belt_warning_system",
    "חיישני לחץ אוויר": "airpressure_sensors",
    "מערכת זיהוי תמרורים": "road_sign_recognition",
    "נפח תא מטען (ליטר)": "trunk_volume_in_liters",
    "נפח תא מטען בקיפול מושבים (ליטר)": "trunk_volume_in_seat_folding",
    "מרווח ראש מושב קדמי (ס״מ)": "front_seat_headroom_in_cm",
    "מרווח ראש מושב אחורי (ס״מ)": "rear_seat_headroom_in_cm",
    "גובה (ס''מ)": "height_in_cm",
    "מרווח מותניים מושב קדמי (ס״מ)": "front_seat_waist_in_cm",
    "מרווח מותניים מושב אחורי (ס״מ)": "rear_seat_waist_in_cm",
    "מרווח רגליים מושב קדמי (ס״מ)": "front_legroom_in_cm",
    "מרווח רגליים מושב אחורי (ס״מ)": "rear_legroom_in_cm",
    "אורך (ס''מ)": "length_in_cm",
    "מרווח כתפיים מושב קדמי (ס״מ)": "front_seat_shoulder_in_cm",
    "מרווח כתפיים מושב אחורי (ס״מ)": "rear_seat_shoulder_in_cm",
    "רוחב (ס''מ)": "width_in_cm",
    "גלגלים קדמיים": "front_wheels",
    "נפח מיכל דלק (ליטרים)": "full_tank_volume_in_liters",
    "משקל מינימלי (ק''ג)": "minimal_weight_in_kg",
    "משקל מקסימלי (ק''ג)": "maximal_weight_in_kg",
    "גלגלים אחוריים": "rear_wheels",
    "בסיס גלגלים (ס''מ)": "wheelbase_in_cm",
    "סאב וופר": "subwoofer",
    "בלוטות'": "bluetooth",
    "שליטה אחורית במערכת מיזוג": "rear_control_air_conditioning",
    "מערכת מיזוג": "air_conditioning",
    "מספר איזורי מיזוג": "number_of_air_conditioning_locations",
    "בקרת שיוט": "cruise_control",
    "כיסא נהג מחומם": "driver_heated_seat",
    "פנסי ערפל": "fog_lights",
    "פנס קדמי": "head_light",
    "כיסא נוסע קדמי מחומם": "heated_front_passenger_seat",
    "חלונות חשמליים": "electric_windows",
    "חיישני גשם": "rain_sensors",
    "כיסא אחורי מחומם": "heated_rear_passenger_seat",
    "חלון בגג": "roof_window",
    "חלונות כהים": "dark_windows",
    "חישוקים": "hoops",
}

DATABASE_COLUMNS = {
    "city": "TEXT",
    "price": "INTEGER",
    "tire_type": "TEXT",
    "tire_width": "INTEGER",
    "height_ratio": "INTEGER",
    "wheel_diameter": "INTEGER",
    "new_car_price": "INTEGER",
    "turbo": "TEXT",
    "finish_level": "TEXT",
    "number_of_doors": "INTEGER",
    "number_of_seats": "INTEGER",
    "avrage_fuel_consumption": "INTEGER",
    "avrage_fuel_consumption_city": "INTEGER",
    "avrage_fuel_consumption_highway": "INTEGER",
    "fuel_type": "TEXT",
    "gearbox": "TEXT",
    "horsepower": "INTEGER",
    "max_speed": "INTEGER",
    "max_torque": "INTEGER",
    "number_of_cylinders": "INTEGER",
    "number_of_gears": "INTEGER",
    "rounds_per_minute_for_max_power": "INTEGER",
    "rounds_per_minute_for_max_torque": "INTEGER",
    "zero_to_100_km_in_seconds": "INTEGER",
    "automatic_high_beam": "BINARY",
    "dead_vehicle_monitoring_system": "BINARY",
    "independent_emergency_break": "BINARY",
    "abs": "BINARY",
    "turn_tracking_headlights": "BINARY",
    "cancel_airbag": "BINARY",
    "isofix": "BINARY",
    "lane_departure_warning_system": "BINARY",
    "number_of_airbags": "INTEGER",
    "seat_belt_warning_system": "BINARY",
    "airpressure_sensors": "BINARY",
    "road_sign_recognition": "BINARY",
    "trunk_volume_in_liters": "INTEGER",
    "trunk_volume_in_seat_folding": "INTEGER",
    "front_seat_headroom_in_cm": "INTEGER",
    "rear_seat_headroom_in_cm": "INTEGER",
    "height_in_cm": "INTEGER",
    "front_seat_waist_in_cm": "INTEGER",
    "rear_seat_waist_in_cm": "INTEGER",
    "front_legroom_in_cm": "INTEGER",
    "rear_legroom_in_cm": "INTEGER",
    "length_in_cm": "INTEGER",
    "front_seat_shoulder_in_cm": "INTEGER",
    "rear_seat_shoulder_in_cm": "INTEGER",
    "width_in_cm": "INTEGER",
    "full_tank_volume_in_liters": "INTEGER",
    "minimal_weight_in_kg": "INTEGER",
    "maximal_weight_in_kg": "INTEGER",
    "wheelbase_in_cm": "INTEGER",
    "subwoofer": "BINARY",
    "bluetooth": "BINARY",
    "rear_control_air_conditioning": "BINARY",
    "air_conditioning": "TEXT",
    "number_of_air_conditioning_locations": "INTEGER",
    "cruise_control": "BINARY",
    "driver_heated_seat": "BINARY",
    "fog_lights": "BINARY",
    "head_light": "TEXT",
    "heated_front_passenger_seat": "BINARY",
    "electric_windows": "INTEGER",
    "rain_sensors": "BINARY",
    "heated_rear_passenger_seat": "BINARY",
    "roof_window": "BINARY",
    "dark_windows": "BINARY",
    "hoops": "TEXT",
    "carName": "TEXT",
    "year": "INTEGER",
    "engine": "INTEGER",
    "current_km": "INTEGER",
    "hand": "INTEGER",
    "color": "TEXT",
    "original_ownership": "TEXT",
    "next_test": "TEXT",
    "annual_licensing_fee": "INTEGER",
}


# DELETE THIS LATER
DEMO_DATA = [{
    "carName": "מאז'דה  3",
    "year": "2021",
    "engine": "1998",
    "current_km": "8,000",
    "hand": "2",
    "gearbox": "אוטומטית",
    "color": "שחור מטלי",
    "original_ownership": "פרטית",
    "next_test": "2",
    "annual_licensing_fee": "2,130 ₪",
    "new_car_price": "155,000 ₪",
    "city": "בת ים",
    "price": "136,000 ₪",
    "number_of_doors": "4",
    "number_of_seats": "5",
    "avrage_fuel_consumption": "13.9",
    "avrage_fuel_consumption_city": "18.9",
    "avrage_fuel_consumption_highway": "14.1",
    "fuel_type": "בנזין",
    "horsepower": "165",
    "max_speed": "208",
    "max_torque": "2,087.4",
    "number_of_cylinders": "4",
    "number_of_gears": "6",
    "rounds_per_minute_for_max_power": "6000",
    "rounds_per_minute_for_max_torque": "4,000",
    "zero_to_100_km_in_seconds": "8.5",
    "automatic_high_beam": 1,
    "independent_emergency_break": 1,
    "abs": 1,
    "turn_tracking_headlights": 1,
    "cancel_airbag": 1,
    "isofix": 1,
    "lane_departure_warning_system": 1,
    "number_of_airbags": "7",
    "seat_belt_warning_system": 1,
    "airpressure_sensors": 1,
    "road_sign_recognition": 0,
    "trunk_volume_in_liters": "444",
    "front_seat_headroom_in_cm": "96.5",
    "rear_seat_headroom_in_cm": "94.7",
    "height_in_cm": "144",
    "front_legroom_in_cm": "107.5",
    "rear_legroom_in_cm": "89.1",
    "length_in_cm": "466",
    "front_seat_shoulder_in_cm": "141.4",
    "rear_seat_shoulder_in_cm": "135.9",
    "width_in_cm": "179.5",
    "tire_type": "R",
    "tire_width": "215",
    "height_ratio": "45",
    "wheel_diameter": "18",
    "full_tank_volume_in_liters": "51",
    "maximal_weight_in_kg": "1,870",
    "minimal_weight_in_kg": "1,454",
    "wheelbase_in_cm": "272.5",
    "subwoofer": 0,
    "rear_control_air_conditioning": 0,
    "air_conditioning": "אוטומטי",
    "number_of_air_conditioning_locations": "2",
    "cruise_control": 1,
    "driver_heated_seat": 0,
    "head_light": "לד",
    "heated_front_passenger_seat": 0,
    "electric_windows": "4",
    "rain_sensors": 1,
    "heated_rear_passenger_seat": 0,
    "roof_window": 1,
    "hoops": "סגסוגת"
}]
