CAR_PROPERTIES = [
    "carName",
    "year",
    "engine",
    "current_km",
    "hand",
    "gearbox",
    "color",
    "original_ownership",
    "next_test",
    "annual_licensing_fee"
]


# SPECIFICATIONS_PROPERTIES = [
#     "finish_level",
#     "number_of_doors",
#     "number_of_seats",
#     "avrage_fuel_consumption",
#     "avrage_fuel_consumption_city",
#     "avrage_fuel_consumption_highway",
#     "fuel_type",
#     "gearbox",
#     "horsepower",
#     "max_speed",
#     "max_torque",
#     "number_of_cylinders",
#     "number_of_gears",
#     "rounds_per_minute_for_max_power",
#     "rounds_per_minute_for_max_torque",
#     "zero_to_100_km_in_seconds",
#     "automatic_high_beam",
#     "dead_vehicle_monitoring_system",
#     "independent_emergency_break",
#     "abs",
#     "turn_tracking_headlights",
#     "cancel_airbag",
#     "isofix",
#     "lane_departure_warning_system",
#     "number_of_airbags",
#     "seat_belt_warning_system",
#     "airpressure_sensors",
#     "road_sign_recognition",
#     "trunk_volume_in_liters",
#     "front_seat_headroom_in_cm",
#     "rear_seat_headroom_in_cm",
#     "height_in_cm",
#     "front_legroom_in_cm",
#     "rear_legroom_in_cm",
#     "length_in_cm",
#     "front_seat_shoulder_in_cm",
#     "rear_seat_shoulder_in_cm",
#     "width_in_cm",
#     "front_wheels",
#     "full_tank_volume_in_liters",
#     "minimal_weight_in_kg",
#     "rear_wheels",
#     "wheelbase_in_cm",
#     "subwoofer",
#     "bluetooth",
#     "rear_control_air_conditioning",
#     "air_conditioning",
#     "number_of_air_conditioning_locations",
#     "cruise_control",
#     "driver_heated_seat",
#     "fog_lights",
#     "head_light",
#     "heated_front_passenger_seat",
#     "electric_windows",
#     "rain_sensors",
#     "heated_rear_passenger_seat",
#     "roof_window",
#     "dark_windows",
#     "hoops",
# ]


SPECIFICATIONS_PROPERTIES_TRANSLATIONS = {
    "טורבו": "turbo",
    "רמת גימור": "finish_level",
    "מספר דלתות": "number_of_doors",
    "מקומות ישיבה": "number_of_seats",
    "צריכת דלק ממוצעת (ק''מ/ליטר)": "avrage_fuel_consumption",
    "צריכת דלק בינעירונית (ק''מ/ליטר)": "avrage_fuel_consumption_city",
    "צריכת דלק עירונית (ק''מ/ליטר)": "avrage_fuel_consumption_highway",
    "סוג דלק": "fuel_type",
    "תיבת הילוכים": "gearbox",
    "הספק מירבי (כ''ס)": "horsepower",
    "מהירות מירבית (קמ''ש)": "max_speed",
    "מומנט מירבי (קג''מ)": "max_torque",
    "מספר צילינדרים": "number_of_cylinders",
    "מספר הילוכים": "number_of_gears",
    "סל''ד להספק מירבי": "rounds_per_minute_for_max_power",
    "סל''ד למומנט מירבי": "rounds_per_minute_for_max_torque",
    "אפס למאה קמ''ש (שניות)": "zero_to_100_km_in_seconds",
    "אורות גבוהים אוטומטיים": "automatic_high_beam",
    "מערכת לניטור רכב בשטח מת": "dead_vehicle_monitoring_system",
    "מערכת לבלימת חירום עצמאית": "independent_emergency_break",
    "ABS": "abs",
    "פנסים עוקבי פנייה": "turn_tracking_headlights",
    "ביטול כרית אוויר לנוסע": "cancel_airbag",
    "איזופיקס (ISOFIX)": "isofix",
    "מערכת להתרעת סטייה מנתיב": "lane_departure_warning_system",
    "מספר כריות אוויר": "number_of_airbags",
    "אזהרת חגורת בטיחות": "seat_belt_warning_system",
    "חיישני לחץ אוויר": "airpressure_sensors",
    "מערכת זיהוי תמרורים": "road_sign_recognition",
    "נפח תא מטען (ליטר)": "trunk_volume_in_liters",
    "נפח תא מטען בקיפול מושבים (ליטר)": "trunk_volume_in_seat_folding",
    "מרווח ראש מושב קדמי (ס״מ)": "front_seat_headroom_in_cm",
    "מרווח ראש מושב אחורי (ס״מ)": "rear_seat_headroom_in_cm",
    "גובה (ס''מ)": "height_in_cm",
    "מרווח מותניים מושב קדמי (ס״מ)": "front_seat_waist_in_cm",
    "מרווח מותניים מושב אחורי (ס״מ)": "rear_seat_waist_in_cm",
    "מרווח רגליים מושב קדמי (ס״מ)": "front_legroom_in_cm",
    "מרווח רגליים מושב אחורי (ס״מ)": "rear_legroom_in_cm",
    "אורך (ס''מ)": "length_in_cm",
    "מרווח כתפיים מושב קדמי (ס״מ)": "front_seat_shoulder_in_cm",
    "מרווח כתפיים מושב אחורי (ס״מ)": "rear_seat_shoulder_in_cm",
    "רוחב (ס''מ)": "width_in_cm",
    "גלגלים קדמיים": "front_wheels",
    "נפח מיכל דלק (ליטרים)": "full_tank_volume_in_liters",
    "משקל מינימלי (ק''ג)": "minimal_weight_in_kg",
    "משקל מקסימלי (ק''ג)": "maximal_weight_in_kg",
    "גלגלים אחוריים": "rear_wheels",
    "בסיס גלגלים (ס''מ)": "wheelbase_in_cm",
    "סאב וופר": "subwoofer",
    "בלוטות'": "bluetooth",
    "שליטה אחורית במערכת מיזוג": "rear_control_air_conditioning",
    "מערכת מיזוג": "air_conditioning",
    "מספר איזורי מיזוג": "number_of_air_conditioning_locations",
    "בקרת שיוט": "cruise_control",
    "כיסא נהג מחומם": "driver_heated_seat",
    "פנסי ערפל": "fog_lights",
    "פנס קדמי": "head_light",
    "כיסא נוסע קדמי מחומם": "heated_front_passenger_seat",
    "חלונות חשמליים": "electric_windows",
    "חיישני גשם": "rain_sensors",
    "כיסא אחורי מחומם": "heated_rear_passenger_seat",
    "חלון בגג": "roof_window",
    "חלונות כהים": "dark_windows",
    "חישוקים": "hoops",
}
