# Few constants are defined in this file for the benefit of use in the EDA section :)

col_numeric = ['price',
               'tire_width',
               'height_ratio',
               'wheel_diameter',
               'new_car_price',
               'number_of_doors',
               'number_of_seats',
               'avrage_fuel_consumption',
               'avrage_fuel_consumption_city',
               'horsepower',
               'max_speed',
               'max_torque',
               'number_of_cylinders',
               'number_of_gears',
               'rounds_per_minute_for_max_power',
               'rounds_per_minute_for_max_torque',
               'avrage_fuel_consumption_highway',
               'zero_to_100_km_in_seconds',
               'number_of_airbags',
               'trunk_volume_in_liters',
               'trunk_volume_in_seat_folding',
               'front_seat_headroom_in_cm',
               'rear_seat_headroom_in_cm',
               'height_in_cm',
               'front_seat_waist_in_cm',
               'rear_seat_waist_in_cm',
               'front_legroom_in_cm',
               'rear_legroom_in_cm',
               'length_in_cm',
               'front_seat_shoulder_in_cm',
               'rear_seat_shoulder_in_cm',
               'width_in_cm',
               'full_tank_volume_in_liters',
               'minimal_weight_in_kg',
               'maximal_weight_in_kg',
               'wheelbase_in_cm',
               'number_of_air_conditioning_locations',
               'hoops',
               'year',
               'engine',
               'current_km',
               'hand',
               'original_ownership',
               'next_test',
               'annual_licensing_fee']


col_strings = [
    "fuel_type",
    'head_light',
    'car_company',
    'color',
    'city',
]
